import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const statusRoute = readFileSync(new URL('../app/api/control-panel/status/route.ts', import.meta.url), 'utf8')
const sessionRoute = readFileSync(new URL('../app/api/control-panel/session/route.ts', import.meta.url), 'utf8')
const passwordRoute = readFileSync(new URL('../app/api/control-panel/password/route.ts', import.meta.url), 'utf8')
const setupRoute = readFileSync(new URL('../app/api/control-panel/setup/route.ts', import.meta.url), 'utf8')
const recoverRoute = readFileSync(new URL('../app/api/control-panel/recover/route.ts', import.meta.url), 'utf8')
const page = readFileSync(new URL('../app/control-panel/page.tsx', import.meta.url), 'utf8')
const legacyPage = readFileSync(new URL('../app/launch-control/page.tsx', import.meta.url), 'utf8')
const launch = readFileSync(new URL('../lib/launch.ts', import.meta.url), 'utf8')
const auth = readFileSync(new URL('../lib/controlPanelAuth.ts', import.meta.url), 'utf8')
const password = readFileSync(new URL('../lib/controlPanelPassword.ts', import.meta.url), 'utf8')
const ownerOperations = readFileSync(new URL('../lib/ownerOperations.ts', import.meta.url), 'utf8')
const lifecycleRoute = readFileSync(new URL('../app/api/extension/lifecycle/route.ts', import.meta.url), 'utf8')
const credentialMigration = readFileSync(new URL('../supabase/migrations/006_control_panel_credentials.sql', import.meta.url), 'utf8')
const operationalEventsMigration = readFileSync(new URL('../supabase/migrations/007_operational_events.sql', import.meta.url), 'utf8')
const abuseMigration = readFileSync(new URL('../supabase/migrations/20260615203641_abuse_controls.sql', import.meta.url), 'utf8')
const lifecycleMigration = readFileSync(new URL('../supabase/migrations/20260616220803_extension_lifecycle_telemetry.sql', import.meta.url), 'utf8')

test('control panel is owner-gated and read-only', () => {
  assert.match(statusRoute, /verifyControlPanelBearer/)
  assert.match(sessionRoute, /verifyOwnerPassword/)
  assert.match(passwordRoute, /saveControlPanelPassword/)
  assert.match(auth, /verifyControlPanelSessionToken/)
  assert.doesNotMatch(page, /LAUNCH_CONTROL_PASSWORD/)
  assert.doesNotMatch(page, /method:\s*['"]DELETE['"]/)
  assert.doesNotMatch(page, /method:\s*['"]PATCH['"]/)
})

test('control panel supports first-time owner setup and password recovery', () => {
  assert.match(setupRoute, /saveControlPanelCredential/)
  assert.match(setupRoute, /isControlPanelSetupTokenRequired/)
  assert.match(setupRoute, /verifyControlPanelSetupToken/)
  assert.match(setupRoute, /setupTokenRequired/)
  assert.match(setupRoute, /Control Panel owner setup is locked/)
  assert.match(setupRoute, /recoveryEmail/)
  assert.match(sessionRoute, /setupRequired/)
  assert.match(recoverRoute, /sendControlPanelRecoveryEmail/)
  assert.match(passwordRoute, /verifyControlPanelResetToken/)
  assert.match(password, /CONTROL_PANEL_SETUP_TOKEN/)
  assert.match(password, /timingSafeEqual\(expected, provided\)/)
  assert.match(password, /scrypt:v1/)
  assert.match(password, /control_panel_credentials/)
  assert.match(page, /Create owner/)
  assert.match(page, /Owner setup token/)
  assert.match(page, /setupTokenRequired/)
  assert.match(page, /Forgot password\?/)
  assert.match(page, /Recovery email/)
  assert.match(page, /Change password/)
  assert.match(credentialMigration, /create table if not exists public\.control_panel_credentials/)
  assert.match(credentialMigration, /username text not null/)
  assert.match(credentialMigration, /recovery_email text not null/)
  assert.match(credentialMigration, /revoke all on table public\.control_panel_credentials from anon, authenticated/)
})

test('control panel reports owner operations metrics', () => {
  assert.match(statusRoute, /getOwnerOperationsSnapshot/)
  assert.match(ownerOperations, /promoSummary/)
  assert.match(ownerOperations, /userSummary/)
  assert.match(ownerOperations, /analysisSummary/)
  assert.match(ownerOperations, /recentHighRisk/)
  assert.match(ownerOperations, /issueSummary/)
  assert.match(ownerOperations, /trend14d/)
  assert.match(ownerOperations, /riskDistribution/)
  assert.match(ownerOperations, /blockedAttempts24h/)
  assert.match(ownerOperations, /extensionSummary/)
  assert.match(ownerOperations, /assigned_at/)
  assert.match(ownerOperations, /extension_installations/)
  assert.match(ownerOperations, /extension_lifecycle_events/)
  assert.match(ownerOperations, /promo_claim_attempts/)
  assert.match(ownerOperations, /requester_email=not\.is\.null/)
  assert.match(operationalEventsMigration, /create table if not exists public\.operational_events/)
  assert.match(operationalEventsMigration, /revoke all on table public\.operational_events from anon, authenticated/)
  assert.match(abuseMigration, /create table if not exists public\.promo_claim_attempts/)
})

test('extension lifecycle telemetry is hashed and owner-visible', () => {
  assert.match(lifecycleRoute, /securityHash\(`extension-install:\$\{input\.installId\}`\)/)
  assert.match(lifecycleRoute, /checkRateLimit\(`extension-lifecycle:\$\{ip\}`/)
  assert.match(lifecycleRoute, /EVENT_TYPES = \['install', 'update', 'uninstall'\] as const/)
  assert.match(lifecycleRoute, /EVENT_TYPE_SET = new Set<string>\(EVENT_TYPES\)/)
  assert.match(lifecycleRoute, /PUBLISHED_EXTENSION_ID = 'fbjajjiepjmcmkcidfbmjbjmmegokhif'/)
  assert.match(lifecycleRoute, /PUBLISHED_EXTENSION_ORIGIN = `chrome-extension:\/\/\$\{PUBLISHED_EXTENSION_ID\}`/)
  assert.match(lifecycleRoute, /isAllowedTelemetryOrigin/)
  assert.match(lifecycleRoute, /Lifecycle telemetry origin is not allowed/)
  assert.doesNotMatch(lifecycleRoute, /requester_email|fromEmail|subject|email_body|raw_ip/)
  assert.match(lifecycleMigration, /create table if not exists public\.extension_installations/)
  assert.match(lifecycleMigration, /install_id_hash text primary key/)
  assert.match(lifecycleMigration, /revoke all on table public\.extension_installations from anon, authenticated/)
  assert.match(lifecycleMigration, /revoke all on table public\.extension_lifecycle_events from anon, authenticated/)
  assert.match(statusRoute, /GuardScope extension lifecycle telemetry/)
})

test('control panel page renders owner dashboard sections', () => {
  assert.match(page, /Control Center/)
  assert.match(page, /Owner-only operating view/)
  assert.match(page, /Chrome Web Store installs/)
  assert.match(page, /Issues and bugs/)
  assert.match(page, /Promo codes/)
  assert.match(page, /Scan analytics/)
  assert.match(page, /High-risk scans/)
  assert.match(page, /Recent accounts/)
  assert.match(page, /Data handling/)
  assert.match(page, /Recent claim attempts/)
  assert.match(page, /Only assigned or redeemed codes/)
  assert.match(page, /promoDisplayStatus/)
})

test('legacy launch control page redirects to control panel', () => {
  assert.match(legacyPage, /redirect\('\/control-panel'\)/)
})

test('launch config uses corrected Chrome Web Store URL', () => {
  assert.match(launch, /fbjajjiepjmcmkcidfbmjbjmmegokhif/)
  assert.doesNotMatch(launch, /fbjajijepjmcmkcidfbmjbjmmegokhif/)
  assert.doesNotMatch(page, /fbjajijepjmcmkcidfbmjbjmmegokhif/)
})
